version: "3.6"

services:
  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./:/app/
    environment:
      API_URL: http://localhost:8080/api-doc
      OAUTH2_REDIRECT_URL: http://localhost:8888/oauth2-redirect.html
      OAUTH2_CLIENTID: ch0p4TrH0ITII6iwSfql8iJHunptDycZ
    ports:
      - 8888:8080

  bare: &app
    image: node:10
    working_dir: /app/
    command: yarn dev:web
    volumes:
      - ./:/app/
      - yarn-cache:/usr/local/share/.cache/yarn/v2
      - node_modules:/app/node_modules/
    environment:
      APP_VERSION: 0.1.0-snapshot
      ENVIRONMENT_NAME: dev
      USE_SWAGGER_VALIDATION: "true"
      AUTH0_ENABLED: "true"
      AUTH0_ISSUER: "two-white-guys.eu.auth0.com"
      AUTH0_AUDIENCE: "some-example-backend"

  full:
    <<: *app
    ports:
      - 8080:8080
    depends_on:
      - swagger

volumes:
  node_modules: {}
  yarn-cache: {
    external: true
  }
